### ISSUE TITLE
Inexistent executable

### ISSUE THREAD

**Issue by ssakura12** [Tornadocraver/GoPro-Video-Recovery#1]
Hi Sir,

You are talking about an executable that has to be run (2. Run the executable file (as an Administrator if you don't have read/write permissions)), but in this project is not present an executable file, excepting the 2s executables files that are used for this project (ffmpeg, recover_mp4). However, I tried to run the GoPro Video Recovery.sln project but there are 114 errors after Rebuild Solution was performed. . Could you help me with an idea about what I'm doing wrong/where is the executable file?

Thank you Sir!

**Comment by Tornadocraver** [comment]
Hi there,

The executable can be found inside the .zip file from the latest build. You can click on the "Windows (32-bit)" link on the main page of this repository, or just [click here](https://github.com/Tornadocraver/GoPro-Video-Recovery/releases/latest) to see the latest releases.

Hope this helps!

**Comment by ssakura12** [comment]
Thank you! It helps. I found the executable, but it doesn't work. I followed the steps from README, but with any video i tested, i got the same error: "An error occurred while reading from the muxing process". 
Can you, please, help me to solve this?
All the best!

**Comment by Tornadocraver** [comment]
Sorry for the long delay in responding - I was not notified of your comment. Were you able to get it working? (Or do you even need it anymore?)

**Comment by Tornadocraver** [comment]
Closing due to no update.
